Insert into estado (uf, nome, ddd, idRegiao) values ('AC', 'Acre', 68, 1);
Insert into estado (uf, nome, ddd, idRegiao) values ('AL', 'Alagoas', 82, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('AP', 'Amapá', 96, 1);
Insert into estado (uf, nome, ddd, idRegiao) values ('AM', 'Amazonas', 92, 1);
Insert into estado (uf, nome, ddd, idRegiao) values ('BA', 'Bahia', 71, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('CE', 'Ceará', 85, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('DF', 'Distrito Federal', 61, 3);
Insert into estado (uf, nome, ddd, idRegiao) values ('ES', 'Espírito Santo', 27, 4);
Insert into estado (uf, nome, ddd, idRegiao) values ('GO', 'Goiás', 62, 3);
Insert into estado (uf, nome, ddd, idRegiao) values ('MA', 'Maranhão', 98, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('MT', 'Mato Grosso', 65, 3);
Insert into estado (uf, nome, ddd, idRegiao) values ('MS', 'Mato Grosso do Sul', 67, 3);
Insert into estado (uf, nome, ddd, idRegiao) values ('MG', 'Minas Gerais', 31, 4);
Insert into estado (uf, nome, ddd, idRegiao) values ('PA', 'Pará', 91, 1);
Insert into estado (uf, nome, ddd, idRegiao) values ('PB', 'Paraíba', 83, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('PR', 'Paraná', 41, 5);
Insert into estado (uf, nome, ddd, idRegiao) values ('PE', 'Pernambuco', 81, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('PI', 'Piauí', 86, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('RJ', 'Rio de Janeiro', 21, 4);
Insert into estado (uf, nome, ddd, idRegiao) values ('RN', 'Rio Grande do Norte', 84, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('RS', 'Rio Grande do Sul', 51, 5);
Insert into estado (uf, nome, ddd, idRegiao) values ('RO', 'Rondônia', 69, 1);
Insert into estado (uf, nome, ddd, idRegiao) values ('RR', 'Roraima', 95, 1);
Insert into estado (uf, nome, ddd, idRegiao) values ('SC', 'Santa Catarina', 47, 5);
Insert into estado (uf, nome, ddd, idRegiao) values ('SP', 'São Paulo', 11, 4);
Insert into estado (uf, nome, ddd, idRegiao) values ('SE', 'Sergipe', 79, 2);
Insert into estado (uf, nome, ddd, idRegiao) values ('TO', 'Tocantins', 63, 2);