insert into operadora (nome) values ('TIM'); -- 1
insert into operadora (nome) values ('OI'); -- 2
insert into operadora (nome) values ('CLARO'); -- 3
insert into operadora (nome) values ('VIVO'); -- 4
insert into operadora (nome) values ('NOS'); -- 5
insert into operadora (nome) values ('NOWO'); -- 6
insert into operadora (nome) values ('MEO'); -- 7
insert into operadora (nome) values ('NEXTEL'); -- 8
insert into operadora (nome) values ('EMBRATEL'); -- 9
insert into operadora (nome) values ('SERCOMTEL'); -- 10